"""baseline: schema atual

Revision ID: 61a73b52f4cf
Revises: 
Create Date: 2026-08-01 19:47:25.006115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a73b52f4cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('colunas', sa.Text(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('entidade', sa.String(length=50), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=20), nullable=False),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entradas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Numeric(), nullable=False),
    sa.Column('data', sa.String(length=50), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lancamentos_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('dados', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requisicoes_materiais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('funcao', sa.String(length=255), nullable=False),
    sa.Column('material', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_criacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarefas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('prestador_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['prestador_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orcamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('valor_orcado', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('projeto_id', 'categoria_id')
    )
    # ### end Alembic commands ###

    # Backfills únicos (antes rodavam a cada boot do backend, em
    # modelUsuarios.py/modelProjetos.py — decisão registrada em STATUS.md
    # Tarefa 3.1: virar migration de dado que roda uma vez é mais correto).
    op.execute("UPDATE usuarios SET is_admin = 1, role = 'admin' WHERE username = 'admin'")
    op.execute("UPDATE usuarios SET role = 'admin' WHERE is_admin = 1")

    _default_cols = (
        '[{"name":"data","label":"Data","type":"text"},'
        '{"name":"categoria","label":"Categoria","type":"select"},'
        '{"name":"item","label":"Item / Descrição","type":"text"},'
        '{"name":"fornecedor","label":"Fornecedor","type":"text"},'
        '{"name":"quantidade","label":"Qtd","type":"number"},'
        '{"name":"unitario","label":"Unitário (R$)","type":"text"},'
        '{"name":"valor","label":"Valor Pago (R$)","type":"text"},'
        '{"name":"forma","label":"Forma","type":"select"},'
        '{"name":"conta","label":"Conta","type":"select"},'
        '{"name":"obs","label":"Observações","type":"textarea"}]'
    )
    op.execute(
        sa.text(
            "UPDATE projetos SET colunas = :cols "
            "WHERE id = 1 AND (colunas IS NULL OR colunas = '[]' OR colunas = '')"
        ).bindparams(cols=_default_cols)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orcamentos')
    op.drop_table('tarefas')
    op.drop_table('requisicoes_materiais')
    op.drop_table('lancamentos_v2')
    op.drop_table('entradas')
    op.drop_table('contas')
    op.drop_table('categorias')
    op.drop_table('auditoria')
    op.drop_table('usuarios')
    op.drop_table('projetos')
    op.drop_table('empresas')
    # ### end Alembic commands ###
